
export const SELECT_FEED = 'SELECT_FEED'
export const INVALIDATE_FEED = 'INVALIDATE_FEED'
export const REQUEST_DATAPOINTS = 'REQUEST_DATAPOINTS'
export const RECEIVE_DATAPOINTS = 'RECEIVE_DATAPOINTS'
export const REQUEST_LAST_VALUE = 'REQUEST_LAST_VALUE'
export const RECEIVE_LAST_VALUE = 'RECEIVE_LAST_VALUE'
export const FIRE_ROUTE_TRANSITION = 'FIRE_ROUTE_TRANSITION'
